// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sirena.Taxi.Orders.Domain;

#nullable disable

namespace Sirena.Taxi.Orders.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220804062741_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sirena.Taxi.Orders.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("DepartureAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departure_address");

                    b.Property<double>("DepartureLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("departure_latitude");

                    b.Property<double>("DepartureLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("departure_longitude");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_address");

                    b.Property<double>("DestinationLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("destination_latitude");

                    b.Property<double>("DestinationLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("destination_longitude");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<bool>("ResponseReceived")
                        .HasColumnType("boolean")
                        .HasColumnName("response_received");

                    b.Property<int>("StateCode")
                        .HasColumnType("integer")
                        .HasColumnName("state_code");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_order_requests");

                    b.ToTable("order_requests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
